project:
  type: website

website:
  title: "GISProject"
  navbar:
    left:
      - href: Intro.qmd
        text: Introduction
      - href: Methodology.qmd
        text: Methodology
      - href: analysis.qmd
        text: Analysis
      - href: findings.qmd
        text: Result & Discussion 
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

